name: Android Nightly

on:
  push:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/nightly.yml'
jobs:
  build:
    if: github.repository == 'pebble-dev/mobile-app'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Setup System
        run: |
          sudo apt-get -y install libsqlite3-dev
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: flutter test
      - run: flutter build apk --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
